
# Configure notification
notifications:
  email:
    on_success: never
    on_failure: never

os:
  - linux
  - osx

env:
  - R_VERSION=r-base
  - R_VERSION=mro-base

matrix:
  exclude:
    - os: osx
      env: R_VERSION=mro-base

language: bash

install:
  # Install miniconda
  - source continuous-integration/travis/install.sh
  # Update conda and install packages
  - conda update --yes conda
  - conda install --yes conda-build jinja2 anaconda-client
  - conda config --add channels brimborium

script:
  - mkdir out
  - conda build conda-recipe --output-folder out

after_success:
  - test $TRAVIS_BRANCH = "master" &&
    anaconda -t $CONDA_UPLOAD_TOKEN upload --force out/$TRAVIS_OS_NAME-64/*.tar.bz2

# We only want to build with Travis when pushing to master or PR:
# https://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-
# build-pull-requests-merges-to-master-w-o-redunda/31882307#31882307
branches:
  only:
    - master
