{% set version = '1.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-datamaid
  version: {{ version|replace("-", "_") }}

source:
  fn: dataMaid_1.1.0.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/dataMaid_1.1.0.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dataMaid/dataMaid_1.1.0.tar.gz
  sha256: 5ec8b954a7b3503b030c50bcf96cdec9a6b2f2c5eadb1626048b65c200f397e9

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown, testthat
requirements:
  build:

  host:
    - {{ environ.get('R_VERSION') }}
    - r-ggplot2
    - r-gridextra
    - r-haven
    - r-htmltools
    - r-magrittr
    - r-pander
    - r-robustbase
    - r-whoami

  run:
    - {{ environ.get('R_VERSION') }}
    - r-ggplot2
    - r-gridextra
    - r-haven
    - r-htmltools
    - r-magrittr
    - r-pander
    - r-robustbase
    - r-whoami

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('dataMaid')"           # [not win]
    - "\"%R%\" -e \"library('dataMaid')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ekstroem/dataMaid
  license: GPL-2
  summary: 'Data screening is an important first step of any statistical analysis. dataMaid autogenerates
    a customizable data report with a thorough summary of the checks and the results
    that a human can use to identify possible errors. It provides an extendable suite
    of test for common potential errors in a dataset. '

  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: dataMaid
# Type: Package
# Title: A Suite of Checks for Identification of Potential Errors in a Data Frame as Part of the Data Screening Process
# Version: 1.1.0
# Date: 2018-02-06
# Authors@R: c(person(given="Anne Helby", family="Petersen", email="ahpe@sund.ku.dk", role="aut"), person(given="Claus Thorn", family="Ekstrm", email="ekstrom@sund.ku.dk", role=c("aut", "cre")))
# Description: Data screening is an important first step of any statistical analysis. dataMaid autogenerates a customizable data report with a thorough summary of the checks and the results that a human can use to identify possible errors. It provides an extendable suite of test for common potential errors in a dataset.
# URL: https://github.com/ekstroem/dataMaid
# BugReports: https://github.com/ekstroem/dataMaid/issues
# Depends: ggplot2
# Imports: gridExtra, haven, htmltools, magrittr, methods, pander, robustbase, whoami
# Suggests: knitr, rmarkdown, testthat
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# ByteCompile: true
# License: GPL-2
# RoxygenNote: 6.0.1.9000
# Collate: 'aggregateForBarplot.R' 'aggregateForHistogram.R' 'allCheckFunctions.R' 'allClasses.R' 'allSummaryFunctions.R' 'allVisualFunctions.R' 'allXFunctions.R' 'makeXFunction.R' 'visualFunction.R' 'basicVisual.R' 'summaryFunction.R' 'centralValue.R' 'check.R' 'checkResult.R' 'messageGenerator.R' 'checkFunction.R' 'identifyMissing.R' 'minMax.R' 'classes.R' 'clean.R' 'countMissing.R' 'dataMaid-package.R' 'description.R' 'identifyCaseIssues.R' 'identifyLoners.R' 'identifyNums.R' 'identifyOutliers.R' 'identifyOutliersTBStyle.R' 'identifyWhitespace.R' 'isCPR.R' 'isSingular.R' 'isEmpty.R' 'isKey.R' 'isSupported.R' 'makeCodebook.R' 'makeDataReport.R' 'misc.R' 'quartiles.R' 'render.R' 'setChecks.R' 'setSummaries.R' 'setVisuals.R' 'smartNum.R' 'standardVisual.R' 'summarize.R' 'summaryResult.R' 'uniqueValues.R' 'unpackLabelled.R' 'variableType.R' 'visualize.R'
# NeedsCompilation: no
# Packaged: 2018-02-06 17:08:03 UTC; cld189
# Author: Anne Helby Petersen [aut], Claus Thorn Ekstrm [aut, cre]
# Maintainer: Claus Thorn Ekstrm <ekstrom@sund.ku.dk>
# Repository: CRAN
# Date/Publication: 2018-02-06 17:33:23 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
